networks:
  desafio-rate-limiter-network:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - .docker/redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - desafio-rate-limiter-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    depends_on:
      - redis
    command: sh -c "go run cmd/ratelimitersystem/main.go"
    environment:
      REDIS_HOST: "redis"
    volumes:
      - .:/app
    networks:
      - desafio-rate-limiter-network
    ports:
      - "8080:8080"